Repository pagopa/pagopa-pdf-engine, pull requests merged in 2023-08, with the labels that each got.

#24 [PRDP-85] fix: Added info response body with services info
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
  src/main/java/it/gov/pagopa/pdf/engine/model/AppInfo.java
  src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java
  src/test/resources/META-INF/maven/it.gov.pagopa.project/pdf-engine/pom.properties
Labels: bug, patch, size/small

#23 fix: updated run_docker.sh
  docker/run_docker.sh
Labels: bug, size/small

#25 fix
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
  src/main/java/it/gov/pagopa/pdf/engine/model/AppInfo.java
  src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java
Labels: size/small

#26 fix docker
  Dockerfile
Labels: patch, size/small

#27 fix deploy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch

#28 fix: Service Principal per accesso a KV Int test
  .identity/02_application_action.tf
Labels: size/small

#30 [PRDP-85] fix: Info response body
  pom.xml
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
  src/main/resources-filtered/application.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java
  src/test/resources/META-INF/maven/it.gov.pagopa.project/pdf-engine/pom.properties
Labels: bug, patch, size/small

#29 [PRDP-95] feat update to opentelemetry agent
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#22 Prf test tuning
  performance-test/src/test-types/constant.json
Labels: size/small

#33 fix: Uat deploy
  helm/values-uat.yaml
Labels: size/small

#36 [PRDP-100] feat: Manage NETWORK_IDLE waiting
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
Labels: patch, size/small

#37 Prdp 100 feat add playwright engine
  README.md
  openapi/openapi.json
  performance-test/src/modules/pdf_engine_client.js
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/test/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImplTest.java
Labels: size/small

#38 [PRDP-110] fix: Configure k6 to not ignore response body
  performance-test/src/modules/pdf_engine_client.js
Labels: bug, patch, size/small

#39 [PRDP-111] feat: Add integration test action
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
Labels: enhancement, minor, size/small

#43 fix notification message
  .github/workflows/integration_test.yml
Labels: bug, skip, size/small
