Repository pagopa/pagopa-pdf-engine, pull requests merged in 2023-10, with the labels that each got.

#70 [PRDP-15] feat: Introducing GHA and .opex configs to create dashboard…
  .github/workflows/create_dashboard.yaml
  .identity/00_data.tf
  .identity/application_main.tf
  .identity/application_main_auth.tf
  .opex/java/env/dev/backend.ini
  .opex/java/env/dev/backend.tfvars
  .opex/java/env/dev/config.yaml
  .opex/java/env/dev/terraform.tfvars
  .opex/java/env/prod/backend.ini
  .opex/java/env/prod/backend.tfvars
  .opex/java/env/prod/config.yaml
  .opex/java/env/prod/terraform.tfvars
  .opex/java/env/uat/backend.ini
  .opex/java/env/uat/backend.tfvars
  .opex/java/env/uat/config.yaml
  .opex/java/env/uat/terraform.tfvars
  .opex/node/env/dev/backend.ini
  .opex/node/env/dev/backend.tfvars
  .opex/node/env/dev/config.yaml
  .opex/node/env/dev/terraform.tfvars
  .opex/node/env/prod/backend.ini
  .opex/node/env/prod/backend.tfvars
  .opex/node/env/prod/config.yaml
  .opex/node/env/prod/terraform.tfvars
  .opex/node/env/uat/backend.ini
  .opex/node/env/uat/backend.tfvars
  .opex/node/env/uat/config.yaml
  .opex/node/env/uat/terraform.tfvars
  openapi/openapi_node.json
Labels: skip, size/large

#72 fix: Dash
  .github/workflows/create_dashboard.yml
  .opex/java/env/dev/backend.ini
  .opex/java/env/dev/backend.tfvars
  .opex/java/env/dev/config.yaml
  .opex/java/env/dev/terraform.tfvars
  .opex/node/env/dev/backend.ini
  .opex/node/env/dev/backend.tfvars
  .opex/node/env/dev/config.yaml
  .opex/node/env/dev/terraform.tfvars
Labels: size/small

#73 fix: Dash step 3
  .github/workflows/create_dashboard.yml
  .github/workflows/dash.yml
  .opex/node/env/uat/config.yaml
  .opex/pdf-engine-service-node/env/prod/backend.ini
  .opex/pdf-engine-service-node/env/prod/backend.tfvars
  .opex/pdf-engine-service-node/env/prod/config.yaml
  .opex/pdf-engine-service-node/env/prod/terraform.tfvars
  .opex/pdf-engine-service-node/env/uat/backend.ini
  .opex/pdf-engine-service-node/env/uat/backend.tfvars
  .opex/pdf-engine-service-node/env/uat/config.yaml
  .opex/pdf-engine-service-node/env/uat/terraform.tfvars
  .opex/pdf-engine-service/env/prod/backend.ini
  .opex/pdf-engine-service/env/prod/backend.tfvars
  .opex/pdf-engine-service/env/prod/config.yaml
  .opex/pdf-engine-service/env/prod/terraform.tfvars
  .opex/pdf-engine-service/env/uat/backend.ini
  .opex/pdf-engine-service/env/uat/backend.tfvars
  .opex/pdf-engine-service/env/uat/config.yaml
  .opex/pdf-engine-service/env/uat/terraform.tfvars
Labels: size/small

#75 [PRDP-119] feat: add custom splitAndSpace Helper
  node/package-lock.json
  node/pdf-generate/helpers/splitAndSpace.js
  node/pdf-generate/utils/browserManager.js
Labels: size/large, patch

#76 feat: adding not and eq custom helpers
  node/pdf-generate/helpers/eq.js
  node/pdf-generate/helpers/not.js
  node/pdf-generate/utils/browserManager.js
Labels: patch, size/small

#78 [PRDP-158] feat: Deploy Java engine on App Service
  .devops/deploy-pipelines.yml
  .github/workflows/release-deploy.bck.hybrid
  .github/workflows/release-deploy.yml
Labels: skip, size/small

#79 fix: Az pipe
  .devops/deploy-pipelines.yml
  .github/workflows/release-deploy.yml
Labels: size/small

#80 fix: App service name pipe
  .devops/deploy-pipelines.yml
  .github/workflows/release-deploy.yml
Labels: size/small

#81 chore: Dash prod
  .github/workflows/create_dashboard.yml
Labels: size/small

#84 fix: Opex
  .opex/pdf-engine-service/env/prod/config.yaml
Labels: size/small

#85 feat: Updating overrides for .opex endpoints
  .opex/pdf-engine-service-node/env/prod/config.yaml
  .opex/pdf-engine-service-node/env/uat/config.yaml
  .opex/pdf-engine-service/env/prod/config.yaml
  .opex/pdf-engine-service/env/uat/config.yaml
Labels: skip, size/small

#86 [PRDP-179] feat: introducing content waiting
  node/pdf-generate/handlers.js
Labels: patch, size/small

#87 Fix: waiting for render custom function fix
  node/pdf-generate/handlers.js
Labels: bug, size/small

#88 [PRDP-193] feat: update java version
  .github/maven_code_review/action.yml
  .github/workflows/code_review.yml
  Dockerfile
  pom.xml
Labels: minor, size/small
