Repository pagopa/pagopa-pdf-engine, pull requests merged in 2023-06, with the labels that each got.

#4 [PRDP-13] ci: Updated deploy workflow to avoid using azure pipelines
  .devops/deploy-pipelines-aks.yml
  .devops/deploy-pipelines-standard.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release-deploy.yml
Labels: ignore-for-release, skip

#5 [PRDP-13] ci: Updated check and assign on pr workflows
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
Labels: ignore-for-release, skip

#6 [PRDP-40] ci: Added .identity terraform folder
  .gitignore
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
Labels: ignore-for-release, skip, size/large

#7 [PRDP-13] ci update helm chart
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: ignore-for-release, skip, size/small

#10 [PRDP-13] fix: updated openapi specs
  openapi/openapi.json
Labels: patch, size/small

#12 [PRDP-46] feat: Added check on template field
  src/main/java/it/gov/pagopa/project/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/project/model/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/project/model/GeneratePDFInput.java
  src/main/java/it/gov/pagopa/project/service/impl/ParseRequestBodyServiceImpl.java
  src/test/java/it/gov/pagopa/project/HttpTriggerGeneratePDFFunctionTest.java
Labels: enhancement, patch, size/small

#14 [PRDP-49] ci: Updated uat chart replica numbers
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: patch, size/small

#11 [PRDP-14] feat: Added integration test
  .github/workflows/code_review.yml
  .gitignore
  README.md
  docker/README.md
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/config/properties.json
  integration-test/src/features/generate_pdf.feature
  integration-test/src/input_data/zip_files/template.zip
  integration-test/src/package.json
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/pdf_engine_client.js
  integration-test/src/step_definitions/pdf_engine_step.js
Labels: enhancement, size/large, minor

#15 chore: removed MIT license
  LICENSE
Labels: patch, size/small

#16 feat: Add zipped management
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  local.settings.json
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/project/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/project/model/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/project/model/GeneratePDFInput.java
  src/main/java/it/gov/pagopa/project/service/GeneratePDFService.java
  src/main/java/it/gov/pagopa/project/service/ParseRequestBodyService.java
  src/main/java/it/gov/pagopa/project/service/impl/GeneratePDFServiceImpl.java
  src/main/java/it/gov/pagopa/project/service/impl/ParseRequestBodyServiceImpl.java
  src/main/java/it/gov/pagopa/project/util/Constants.java
  src/test/java/it/gov/pagopa/project/HttpTriggerGeneratePDFFunctionTest.java
  src/test/java/it/gov/pagopa/project/service/impl/GeneratePDFServiceImplTest.java
  src/test/java/it/gov/pagopa/project/service/impl/ParseRequestBodyServiceImplTest.java
Labels: enhancement, size/large, patch
