Repository pagopa/pagopa-pdf-engine, pull requests merged in 2023-09, with the labels that each got.

#44 feat: PRDP-122 rework with node engine
  .github/workflows/code_review.yml
  .gitignore
  Dockerfile
  docker/docker-compose.yml
  integration-test/src/features/generate_pdf.feature
  integration-test/src/step_definitions/pdf_engine_client.js
  integration-test/src/step_definitions/pdf_engine_step.js
  local.settings.json
  node/.gitignore
  node/__mocks__/@anzp/azure-function-multipart.js
  node/jest.config.js
  node/package-lock.json
  node/package.json
  node/pdf-generate/__tests__/index.test.js
  node/pdf-generate/function.json
  node/pdf-generate/index.js
  node/pdf-generate/utils/browserManager.js
  node/pdf-generate/utils/buildUtils.js
  openapi/openapi.json
  performance-test/src/local.environment.json
  performance-test/src/modules/pdf_engine_client.js
  performance-test/src/test-types/load.json
  pom.xml
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
  src/main/java/it/gov/pagopa/pdf/engine/client/PdfEngineClient.java
  src/main/java/it/gov/pagopa/pdf/engine/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineErrorMessage.java
  src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineErrorResponse.java
  src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineResponse.java
  src/main/java/it/gov/pagopa/pdf/engine/service/GeneratePDFService.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/util/ObjectMapperUtils.java
  src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java
  src/test/java/it/gov/pagopa/pdf/engine/client/PdfEngineClientImplTest.java
  src/test/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImplTest.java
  start.sh
Labels: size/large, major

#45 [fix] Fixed app name in chart.yaml
  helm/Chart.yaml
Labels: patch, size/small

#48 [PRDP-134] fix node code review and refactor
  .github/workflows/code_review.yml
  node/__mocks__/@anzp/azure-function-multipart.js
  node/__mocks__/pdf-generate/template.html
  node/package-lock.json
  node/package.json
  node/pdf-generate/__tests__/index.test.js
  node/pdf-generate/handlers.js
  node/pdf-generate/index.js
  node/pdf-generate/utils/browserManager.js
  performance-test/src/test-types/load.json
  pom.xml
  src/main/java/it/gov/pagopa/pdf/engine/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
  src/test/java/it/gov/pagopa/pdf/engine/client/PdfEngineClientImplTest.java
Labels: size/large, minor

#47 [PRDP-123] feat: Use deployment selfhosted runner for integration test
  .github/workflows/integration_test.yml
Labels: enhancement, skip, size/small

#49 [PRDP-133] feat: Configured logback and change logger to SLF4J
  LICENSE
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
  src/main/java/it/gov/pagopa/pdf/engine/exception/CompileTemplateException.java
  src/main/java/it/gov/pagopa/pdf/engine/exception/FillTemplateException.java
  src/main/java/it/gov/pagopa/pdf/engine/exception/GeneratePDFException.java
  src/main/java/it/gov/pagopa/pdf/engine/exception/PDFEngineException.java
  src/main/java/it/gov/pagopa/pdf/engine/exception/RequestBodyParseException.java
  src/main/java/it/gov/pagopa/pdf/engine/exception/UnexpectedRequestBodyFieldException.java
  src/main/java/it/gov/pagopa/pdf/engine/model/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/pdf/engine/model/ErrorMessage.java
  src/main/java/it/gov/pagopa/pdf/engine/model/ErrorResponse.java
  src/main/java/it/gov/pagopa/pdf/engine/model/GeneratePDFInput.java
  src/main/java/it/gov/pagopa/pdf/engine/model/GeneratorType.java
  src/main/java/it/gov/pagopa/pdf/engine/service/GeneratePDFService.java
  src/main/java/it/gov/pagopa/pdf/engine/service/ParseRequestBodyService.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
  src/main/resources-filtered/application.properties
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
  src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java
  src/test/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImplTest.java
  src/test/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImplTest.java
  src/test/java/it/gov/pagopa/pdf/engine/util/HttpResponseMessageMock.java
Labels: enhancement, size/large, minor

#50 fix: info and uat helm
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
Labels: patch, size/small

#51 [PRDP-137] fix: Move working directory to avoid host restart
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
  src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
  src/test/resources/logback-test.xml
Labels: bug, patch, size/small

#52 [test] Removed request to node app in info trigger
  src/main/java/it/gov/pagopa/pdf/engine/Info.java
Labels: patch, size/small

#53 new deploy
  helm/values-uat.yaml
Labels: size/small

#55 [feat] Add more log to pdf generation
  .devops/performance-test-pipelines.yml
  performance-test/src/test-types/constant_minor.json
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/service/GeneratePDFService.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
  src/test/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImplTest.java
Labels: enhancement, patch, size/small

#57 [feat] Added logs with milliseconds to nodejs app
  node/pdf-generate/handlers.js
Labels: enhancement, patch, size/small

#58 [feat] Add logs timestamp node app
  node/pdf-generate/handlers.js
Labels: size/small

#59 [feat] Improved logs readability
  node/pdf-generate/handlers.js
Labels: patch, size/small

#60 feat: Uat perf
  helm/values-uat.yaml
Labels: patch

#61 [feat] Fixed console call
  node/pdf-generate/handlers.js
Labels: patch, size/small

#62 [feat] Implemented optimization for page creation & html opening
  helm/values-dev.yaml
  node/pdf-generate/handlers.js
  node/pdf-generate/index.js
  node/pdf-generate/utils/browserManager.js
Labels: patch, size/small

#63 [revert] Revert merge
  helm/values-dev.yaml
  node/pdf-generate/handlers.js
  node/pdf-generate/index.js
  node/pdf-generate/utils/browserManager.js
Labels: patch, size/small

#64 [fix] Parsed data for template html
  node/pdf-generate/handlers.js
Labels: patch, size/small

#65 [PRDP-142] feat: introduce node devops
  .devops/deploy-pipelines.yml
  .github/workflows/release-deploy.yml
  Dockerfile
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-uat.yaml
  node/Dockerfile
  node/package.json
  node/pdf-generate/handlers.js
  node/pdf-generate/index.js
  performance-test/src/uat.environment.json
  performance-test/src/zip_files/template.zip
  src/main/java/it/gov/pagopa/pdf/engine/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/model/GeneratePDFInput.java
  src/main/java/it/gov/pagopa/pdf/engine/model/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
  start.sh
Labels: size/large, minor

#66 feat: Allow to run performance on bot java and node engine
  .devops/performance-test-pipelines.yml
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/step_definitions/common.js
  node/Dockerfile
  node/package-lock.json
  node/package.json
  node/pdf-generate/__tests__/index.test.js
  node/pdf-generate/handlers.js
  node/pdf-generate/index.js
  node/pdf-generate/utils/browserManager.js
  performance-test/src/uat_java.environment.json
  performance-test/src/uat_node.environment.json
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/client/impl/PdfEngineClientImpl.java
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/pdf/engine/InfoTest.java
  src/test/java/it/gov/pagopa/pdf/engine/client/PdfEngineClientImplTest.java
  src/test/resources/logback-test.xml
Labels: enhancement, patch, size/small

#67 [feat] Updated node app unit tests
  .devops/performance-test-pipelines.yml
  .github/workflows/code_review.yml
  integration-test/src/config/.env.local
  node/package.json
  node/pdf-generate/__tests__/index.test.js
  node/pdf-generate/__tests__/resources/test_template.zip
  node/pdf-generate/handlers.js
  node/pdf-generate/index.js
  src/main/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunction.java
  src/main/java/it/gov/pagopa/pdf/engine/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/model/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/pdf/engine/model/GeneratePDFInput.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/GeneratePDFServiceImpl.java
  src/main/java/it/gov/pagopa/pdf/engine/service/impl/ParseRequestBodyServiceImpl.java
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/pdf/engine/HttpTriggerGeneratePDFFunctionTest.java
  src/test/resources/logback-test.xml
Labels: patch, size/small

#69 Prdp 144 chore reintroducing aps release on devops
  .devops/deploy-pipelines.yml
  .github/workflows/release-deploy.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: skip, size/small

#71 fix: avoid skipping push on app service when not rebuilding docker image
  .github/workflows/release-deploy.yml
Labels: bug, skip, size/small
