Repository pagopa/pagopa-pdf-engine, pull requests merged in 2023-07, with the labels that each got.

#17 [PRDP-19] feat: Add performance test
  .devops/performance-test-pipelines.yml
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/common.js
  performance-test/src/modules/pdf_engine_client.js
  performance-test/src/pdf_engine.js
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
  performance-test/src/zip_files/template.zip
  pom.xml
Labels: enhancement, size/large, minor

#18 [fix-environment-nginx] Changed nginx proxy url environment
  performance-test/nginx/nginx.conf
Labels: size/small

#20 [PRDP-75] Tuning performance tests
  .devops/performance-test-pipelines.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  performance-test/src/test-types/constant.json
Labels: enhancement, patch, size/small
