Repository pagopa/pagopa-pdf-engine, pull requests merged in 2024-06, with the labels that each got.

#108 [VAS-1057] feat: introduced thermal template partials
  node/pdf-generate/partials/notices/paymentInfo.hbs
  node/pdf-generate/partials/notices/paymentMethods.hbs
  node/pdf-generate/partials/notices/thermalHeader.hbs
  node/pdf-generate/partials/notices/thermalPaymentData.hbs
  node/pdf-generate/partials/notices/thermalPaymentInfoInfraction.hbs
  node/pdf-generate/partials/notices/thermalPaymentInfoInfractionImmediate.hbs
  node/pdf-generate/partials/notices/thermalPaymentMethods.hbs
Labels: enhancement, patch, size/small

#110 fix: helpers
  node/pdf-generate/helpers/notices/getOnlinePaymentMethodContent.js
  node/pdf-generate/helpers/notices/getPhysicalPaymentMethodContent.js
Labels: patch, size/small

#111 feat: reworked datamatrix helper to use bwip-js
  node/package.json
  node/pdf-generate/helpers/notices/genDataMatrix.js
Labels: patch, size/small

#112 fix: genDataMatrix.js
  node/pdf-generate/helpers/notices/genDataMatrix.js
Labels: bug, patch, size/small

#113 chore: App service HA
  .github/workflows/release-deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_node.json
  pom.xml
Labels: skip, size/small

#114 feat: updated templates for notice
  node/pdf-generate/helpers/commons/arrayLength.js
  node/pdf-generate/helpers/commons/navigateMatrix.js
  node/pdf-generate/helpers/commons/times.js
  node/pdf-generate/helpers/notices/getOnlinePaymentMethodContent.js
  node/pdf-generate/helpers/notices/getPhysicalPaymentMethodContent.js
  node/pdf-generate/helpers/notices/getRowIndex.js
  node/pdf-generate/helpers/notices/paginator.js
  node/pdf-generate/partials/notices/header.hbs
  node/pdf-generate/partials/notices/paymentBollettino.hbs
  node/pdf-generate/partials/notices/paymentInfo.hbs
  node/pdf-generate/partials/notices/paymentInfoInfraction.hbs
  node/pdf-generate/partials/notices/paymentInfoInfractionP1.hbs
  node/pdf-generate/partials/notices/paymentInfoInfractionP2.hbs
  node/pdf-generate/partials/notices/paymentInfoMultipleInstalments.hbs
  node/pdf-generate/partials/notices/paymentInstalments.hbs
  node/pdf-generate/partials/notices/paymentInstalmentsPoste.hbs
  node/pdf-generate/partials/notices/paymentMethods.hbs
  node/pdf-generate/partials/notices/paymentQR.hbs
  node/pdf-generate/partials/notices/paymentQRCol.hbs
  node/pdf-generate/partials/notices/paymentQRColCompact.hbs
  node/pdf-generate/partials/notices/paymentQRColDense.hbs
  node/pdf-generate/partials/notices/paymentSeparatorInfraction.hbs
  node/pdf-generate/partials/notices/thermalHeader.hbs
  node/pdf-generate/partials/notices/thermalPaymentInfoInfraction.hbs
  node/pdf-generate/partials/notices/thermalPaymentInfoInfractionImmediate.hbs
Labels: size/large, patch

#115 chore: Alert OPEX x apim V2
  .github/workflows/create_dashboard.yml
  .opex/pdf-engine-service-apimv2/env/prod/backend.ini
  .opex/pdf-engine-service-apimv2/env/prod/backend.tfvars
  .opex/pdf-engine-service-apimv2/env/prod/config.yaml
  .opex/pdf-engine-service-apimv2/env/prod/terraform.tfvars
  .opex/pdf-engine-service-node-apimv2/env/prod/backend.ini
  .opex/pdf-engine-service-node-apimv2/env/prod/backend.tfvars
  .opex/pdf-engine-service-node-apimv2/env/prod/config.yaml
  .opex/pdf-engine-service-node-apimv2/env/prod/terraform.tfvars
Labels: skip, size/small

#119 [VAS-1137] new args at deploy pipeline
  .devops/deploy-pipelines.yml
  .github/workflows/release-deploy.yml
Labels: skip, size/small

#120 fix: updated partials
  node/pdf-generate/partials/notices/paymentInstalments.hbs
  node/pdf-generate/partials/notices/paymentPoste.hbs
Labels: bug, patch, size/small
